### ISSUE TITLE
Default Logback config for template should include a rolling file appender

### ISSUE THREAD

**Issue by sbchapin** [sbchapin/quickstart-scala-sbt-native-image.g8#2]
Should provide a better baseline configuration including rolling file appenders, since a huge log consuming disk is typically the first thing that destroys any long-lived application running without oversight (and it'd be nice for naive implementers to not worry about that).

- [Existing logging config](https://github.com/sbchapin/quickstart-scala-sbt-native-image.g8/blob/master/src/main/g8/src/main/resources/logback.xml) (in-repo)
- [Suggested rolling logger](http://logback.qos.ch/apidocs/ch/qos/logback/core/rolling/SizeAndTimeBasedRollingPolicy.html)

_Originally posted by @sbchapin in https://github.com/sbchapin/quickstart-scala-sbt-native-image.g8/pull/1_

**Comment by sbchapin** [comment]
Developed and tested this one with a local build and various configurations of `maxFileSize`, `maxHistory`, `totalSizeCap`, and lots of logs.  Performs as it says on the tin:
```xml
<configuration>

    <property name="pattern-colored" value="[%date] %highlight([%-5level]) [%thread %logger{20} %file:%line] %msg%n"/>
    <property name="pattern" value="[%date] [%-5level] [%thread %logger{20} %file:%line] %msg%n"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${pattern-colored}</pattern>
        </encoder>
    </appender>

    <appender name="ROLLINGFILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/example-scala-cli.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>logs/example-scala-cli-%d{yyyy-MM-dd}.%i.log</fileNamePattern> <!-- rollover daily -->
            <maxFileSize>100MB</maxFileSize> <!-- each file should be at most 100MB -->
            <maxHistory>30</maxHistory> <!-- with up to 30 days worth of history -->
            <totalSizeCap>20GB</totalSizeCap> <!-- and at most 20 GB, preserving more recent logs -->
        </rollingPolicy>
        <encoder>
            <pattern>${pattern}</pattern>
        </encoder>
    </appender>

    <root level="TRACE">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="ROLLINGFILE"/>
    </root>

</configuration>
```

---

However, ❗️ **it does not build with native-image**❗️<details><summary>Click for exception</summary>

```
[error] Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[error] Detailed message:
[error] Trace: 	object java.io.FileOutputStream
[error] 	object ch.qos.logback.core.recovery.ResilientFileOutputStream
[error] 	object ch.qos.logback.core.rolling.RollingFileAppender
[error] 	object ch.qos.logback.core.status.InfoStatus
[error] 	object java.lang.Object[]
[error] 	object java.util.ArrayList
[error] 	object ch.qos.logback.core.BasicStatusManager
[error] 	object ch.qos.logback.classic.LoggerContext
[error] 	object org.slf4j.impl.StaticLoggerBinder
[error] 	field org.slf4j.impl.StaticLoggerBinder.SINGLETON
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.typesafe.sbt.packager.graalvmnativeimage.GraalVMNativeImagePlugin$.buildLocal(GraalVMNativeImagePlugin.scala:104)
[error] 	at com.typesafe.sbt.packager.graalvmnativeimage.GraalVMNativeImagePlugin$.$anonfun$scopedSettings$7(GraalVMNativeImagePlugin.scala:68)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
</details>

Similar issues posted [here](https://github.com/spring-projects-experimental/spring-graal-native/issues/8) and [here](https://github.com/oracle/graal/issues/1323)

Did not push further, no solution currently found (maybe kicking it to run-time via SubstrateVM configuration?)
